// This file is auto-generated by @hey-api/openapi-ts

export const ApiKeyCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scopes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ApiKeyCreate'
} as const;

export const ApiKeyCreatedSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scopes'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        key: {
            type: 'string',
            title: 'Key'
        }
    },
    type: 'object',
    required: ['id', 'name', 'key'],
    title: 'ApiKeyCreated'
} as const;

export const ApiKeyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scopes'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ApiKeyPublic'
} as const;

export const ApiKeysPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApiKeyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApiKeysPublic'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        entity_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Type'
        },
        entity_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Id'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'action'],
    title: 'AuditLogPublic'
} as const;

export const AuditLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        next_cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Cursor'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditLogsPublic'
} as const;

export const Body_files_uploadSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        totp_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Totp Code'
        },
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatMessageSchema = {
    properties: {
        role: {
            type: 'string',
            maxLength: 20,
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['role', 'content'],
    title: 'ChatMessage'
} as const;

export const ChatRequestSchema = {
    properties: {
        messages: {
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            type: 'array',
            title: 'Messages'
        },
        system_prompt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4000
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        }
    },
    type: 'object',
    required: ['messages'],
    title: 'ChatRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        next_cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Cursor'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        read_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'type', 'title'],
    title: 'NotificationPublic'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'NotificationsPublic'
} as const;

export const OrganizationCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'OrganizationCreate'
} as const;

export const OrganizationInviteCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            maxLength: 30,
            title: 'Role',
            default: 'member'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'OrganizationInviteCreate'
} as const;

export const OrganizationInvitePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'organization_id', 'email', 'role', 'status'],
    title: 'OrganizationInvitePublic'
} as const;

export const OrganizationInvitesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrganizationInvitePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrganizationInvitesPublic'
} as const;

export const OrganizationMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'role'],
    title: 'OrganizationMemberPublic'
} as const;

export const OrganizationMembersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrganizationMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrganizationMembersPublic'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        branding: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branding'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug'],
    title: 'OrganizationPublic'
} as const;

export const OrganizationUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        branding: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branding'
        }
    },
    type: 'object',
    title: 'OrganizationUpdate'
} as const;

export const PlanCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 100,
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        amount_cents: {
            type: 'integer',
            title: 'Amount Cents'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'usd'
        },
        billing_interval: {
            type: 'string',
            maxLength: 20,
            title: 'Billing Interval',
            default: 'month'
        },
        trial_days: {
            type: 'integer',
            title: 'Trial Days',
            default: 0
        },
        provider_plan_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Plan Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        features: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Features'
        },
        quotas: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quotas'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'amount_cents'],
    title: 'PlanCreate'
} as const;

export const PlanPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        amount_cents: {
            type: 'integer',
            title: 'Amount Cents'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        billing_interval: {
            type: 'string',
            title: 'Billing Interval'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        trial_days: {
            type: 'integer',
            title: 'Trial Days',
            default: 0
        },
        features: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Features'
        },
        quotas: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quotas'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug', 'amount_cents', 'currency', 'billing_interval', 'is_active'],
    title: 'PlanPublic'
} as const;

export const PlanUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        amount_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount Cents'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        billing_interval: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Billing Interval'
        },
        trial_days: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trial Days'
        },
        provider_plan_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Plan Id'
        },
        features: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Features'
        },
        quotas: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quotas'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'PlanUpdate'
} as const;

export const PlansPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlanPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlansPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PublicConfigSchema = {
    properties: {
        project_name: {
            type: 'string',
            title: 'Project Name'
        },
        support_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Support Email'
        }
    },
    type: 'object',
    required: ['project_name'],
    title: 'PublicConfig'
} as const;

export const RefreshRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshRequest'
} as const;

export const ResendVerificationEmailSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ResendVerificationEmail'
} as const;

export const ScimNameSchema = {
    properties: {
        formatted: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Formatted'
        },
        givenName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Givenname'
        },
        familyName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Familyname'
        }
    },
    type: 'object',
    title: 'ScimName'
} as const;

export const ScimPatchOperationSchema = {
    properties: {
        op: {
            type: 'string',
            title: 'Op',
            default: 'replace'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        value: {
            title: 'Value'
        }
    },
    type: 'object',
    title: 'ScimPatchOperation'
} as const;

export const ScimPatchRequestSchema = {
    properties: {
        schemas: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Schemas',
            default: ['urn:ietf:params:scim:api:messages:2.0:PatchOp']
        },
        active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active'
        },
        displayName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Displayname'
        },
        name: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ScimName'
                },
                {
                    type: 'null'
                }
            ]
        },
        Operations: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ScimPatchOperation'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Operations'
        }
    },
    type: 'object',
    title: 'ScimPatchRequest'
} as const;

export const ScimUserRequestSchema = {
    properties: {
        schemas: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Schemas',
            default: ['urn:ietf:params:scim:schemas:core:2.0:User']
        },
        userName: {
            type: 'string',
            format: 'email',
            title: 'Username'
        },
        displayName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Displayname'
        },
        name: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ScimName'
                },
                {
                    type: 'null'
                }
            ]
        },
        active: {
            type: 'boolean',
            title: 'Active',
            default: true
        }
    },
    type: 'object',
    required: ['userName'],
    title: 'ScimUserRequest'
} as const;

export const SessionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        user_agent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Agent'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'SessionPublic'
} as const;

export const SessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SessionsPublic'
} as const;

export const SubscriptionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        plan: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        current_period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Period Start'
        },
        current_period_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Period End'
        },
        cancel_at_period_end: {
            type: 'boolean',
            title: 'Cancel At Period End',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'provider', 'status'],
    title: 'SubscriptionPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        },
        expires_in: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TotpDisableRequestSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'TotpDisableRequest'
} as const;

export const TotpEnableRequestSchema = {
    properties: {
        password: {
            type: 'string',
            title: 'Password'
        },
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['password', 'code'],
    title: 'TotpEnableRequest'
} as const;

export const TotpSetupRequestSchema = {
    properties: {
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'TotpSetupRequest'
} as const;

export const TotpSetupResponseSchema = {
    properties: {
        secret: {
            type: 'string',
            title: 'Secret'
        },
        otpauth_url: {
            type: 'string',
            title: 'Otpauth Url'
        }
    },
    type: 'object',
    required: ['secret', 'otpauth_url'],
    title: 'TotpSetupResponse'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            type: 'string',
            maxLength: 30,
            title: 'Role',
            default: 'user'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        hashed_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hashed Password'
        },
        totp_secret: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Totp Secret'
        },
        totp_enabled: {
            type: 'boolean',
            title: 'Totp Enabled',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'User'
} as const;

export const UserAccessSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified'
        },
        plan: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlanPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        features: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Features'
        }
    },
    type: 'object',
    required: ['role', 'is_superuser', 'is_verified', 'features'],
    title: 'UserAccess'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            type: 'string',
            maxLength: 30,
            title: 'Role',
            default: 'user'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            type: 'string',
            maxLength: 30,
            title: 'Role',
            default: 'user'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        next_cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Cursor'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerifyEmailRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'VerifyEmailRequest'
} as const;

export const WebhookCreateSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Url'
        },
        secret: {
            type: 'string',
            maxLength: 255,
            minLength: 0,
            title: 'Secret',
            default: ''
        },
        events: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Events'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'WebhookCreate'
} as const;

export const WebhookDeliveriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WebhookDeliveryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WebhookDeliveriesPublic'
} as const;

export const WebhookDeliveryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event: {
            type: 'string',
            title: 'Event'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        attempts: {
            type: 'integer',
            title: 'Attempts'
        },
        response_status: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Response Status'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['id', 'event', 'status', 'attempts'],
    title: 'WebhookDeliveryPublic'
} as const;

export const WebhookPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        events: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Events'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'url', 'is_active'],
    title: 'WebhookPublic'
} as const;

export const WebhookUpdateSchema = {
    properties: {
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        events: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Events'
        }
    },
    type: 'object',
    title: 'WebhookUpdate'
} as const;

export const WebhooksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WebhookPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WebhooksPublic'
} as const;