// This file is auto-generated by @hey-api/openapi-ts

export type ApiKeyCreate = {
    name: string;
    scopes?: Array<(string)>;
};

export type ApiKeyCreated = {
    id: string;
    name: string;
    scopes?: Array<(string)>;
    last_used_at?: (string | null);
    revoked_at?: (string | null);
    created_at?: (string | null);
    key: string;
};

export type ApiKeyPublic = {
    id: string;
    name: string;
    scopes?: Array<(string)>;
    last_used_at?: (string | null);
    revoked_at?: (string | null);
    created_at?: (string | null);
};

export type ApiKeysPublic = {
    data: Array<ApiKeyPublic>;
    count: number;
};

export type AuditLogPublic = {
    id: string;
    action: string;
    entity_type?: (string | null);
    entity_id?: (string | null);
    ip_address?: (string | null);
    detail?: (string | null);
    created_at?: (string | null);
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
    next_cursor?: (string | null);
};

export type Body_files_upload = {
    file: string;
};

export type Body_login_login_access_token = {
    totp_code?: (string | null);
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessage = {
    role: string;
    content: string;
};

export type ChatRequest = {
    messages: Array<ChatMessage>;
    system_prompt?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
    next_cursor?: (string | null);
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    id: string;
    type: string;
    title: string;
    body?: (string | null);
    read_at?: (string | null);
    created_at?: (string | null);
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
};

export type OrganizationCreate = {
    name: string;
};

export type OrganizationInviteCreate = {
    email: string;
    role?: string;
};

export type OrganizationInvitePublic = {
    id: string;
    organization_id: string;
    email: string;
    role: string;
    status: string;
    created_at?: (string | null);
};

export type OrganizationInvitesPublic = {
    data: Array<OrganizationInvitePublic>;
    count: number;
};

export type OrganizationMemberPublic = {
    id: string;
    user_id: string;
    email?: (string | null);
    full_name?: (string | null);
    role: string;
    created_at?: (string | null);
};

export type OrganizationMembersPublic = {
    data: Array<OrganizationMemberPublic>;
    count: number;
};

export type OrganizationPublic = {
    id: string;
    name: string;
    slug: string;
    is_active?: boolean;
    branding?: (string | null);
    created_at?: (string | null);
};

export type OrganizationUpdate = {
    name?: (string | null);
    branding?: (string | null);
};

export type PlanCreate = {
    name: string;
    slug: string;
    description?: (string | null);
    amount_cents: number;
    currency?: string;
    billing_interval?: string;
    trial_days?: number;
    provider_plan_id?: (string | null);
    is_active?: boolean;
    features?: (string | null);
    quotas?: (string | null);
};

export type PlanPublic = {
    id: string;
    name: string;
    slug: string;
    description?: (string | null);
    amount_cents: number;
    currency: string;
    billing_interval: string;
    is_active: boolean;
    trial_days?: number;
    features?: (string | null);
    quotas?: (string | null);
};

export type PlansPublic = {
    data: Array<PlanPublic>;
    count: number;
};

export type PlanUpdate = {
    name?: (string | null);
    description?: (string | null);
    amount_cents?: (number | null);
    currency?: (string | null);
    billing_interval?: (string | null);
    trial_days?: (number | null);
    provider_plan_id?: (string | null);
    features?: (string | null);
    quotas?: (string | null);
    is_active?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PublicConfig = {
    project_name: string;
    support_email?: (string | null);
};

export type RefreshRequest = {
    refresh_token: string;
};

export type ResendVerificationEmail = {
    email: string;
};

export type ScimName = {
    formatted?: (string | null);
    givenName?: (string | null);
    familyName?: (string | null);
};

export type ScimPatchOperation = {
    op?: string;
    path?: (string | null);
    value?: unknown;
};

export type ScimPatchRequest = {
    schemas?: Array<(string)>;
    active?: (boolean | null);
    displayName?: (string | null);
    name?: (ScimName | null);
    Operations?: (Array<ScimPatchOperation> | null);
};

export type ScimUserRequest = {
    schemas?: Array<(string)>;
    userName: string;
    displayName?: (string | null);
    name?: (ScimName | null);
    active?: boolean;
};

export type SessionPublic = {
    id: string;
    ip_address?: (string | null);
    user_agent?: (string | null);
    created_at?: (string | null);
    last_used_at?: (string | null);
    expires_at?: (string | null);
};

export type SessionsPublic = {
    data: Array<SessionPublic>;
    count: number;
};

export type SubscriptionPublic = {
    id: string;
    plan?: (PlanPublic | null);
    provider: string;
    status: string;
    current_period_start?: (string | null);
    current_period_end?: (string | null);
    cancel_at_period_end?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
    expires_in?: (number | null);
};

export type TotpDisableRequest = {
    code: string;
};

export type TotpEnableRequest = {
    password: string;
    code: string;
};

export type TotpSetupRequest = {
    password: string;
};

export type TotpSetupResponse = {
    secret: string;
    otpauth_url: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type User = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: string;
    is_verified?: boolean;
    full_name?: (string | null);
    id?: string;
    hashed_password?: (string | null);
    totp_secret?: (string | null);
    totp_enabled?: boolean;
    created_at?: (string | null);
};

export type UserAccess = {
    role: string;
    is_superuser: boolean;
    is_verified: boolean;
    plan?: (PlanPublic | null);
    features: Array<(string)>;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: string;
    is_verified?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: string;
    is_verified?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
    next_cursor?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    role?: (string | null);
    is_verified?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VerifyEmailRequest = {
    token: string;
};

export type WebhookCreate = {
    url: string;
    secret?: string;
    events?: Array<(string)>;
};

export type WebhookDeliveriesPublic = {
    data: Array<WebhookDeliveryPublic>;
    count: number;
};

export type WebhookDeliveryPublic = {
    id: string;
    event: string;
    status: string;
    attempts: number;
    response_status?: (number | null);
    created_at?: (string | null);
    completed_at?: (string | null);
};

export type WebhookPublic = {
    id: string;
    url: string;
    events?: Array<(string)>;
    is_active: boolean;
    created_at?: (string | null);
};

export type WebhooksPublic = {
    data: Array<WebhookPublic>;
    count: number;
};

export type WebhookUpdate = {
    url?: (string | null);
    is_active?: (boolean | null);
    events?: (Array<(string)> | null);
};

export type AdminAdminOverviewResponse = ({
    [key: string]: (number);
});

export type AdminAdminOrganizationsData = {
    cursor?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminAdminOrganizationsResponse = ({
    [key: string]: unknown;
});

export type AdminAdminUsersData = {
    limit?: number;
    skip?: number;
};

export type AdminAdminUsersResponse = ({
    [key: string]: unknown;
});

export type AdminAdminSetUserStatusData = {
    isActive: boolean;
    userId: unknown;
};

export type AdminAdminSetUserStatusResponse = (User);

export type AdminAdminAuditLogData = {
    cursor?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminAdminAuditLogResponse = (AuditLogsPublic);

export type AdminAdminPlansResponse = (PlansPublic);

export type AdminAdminCreatePlanData = {
    requestBody: PlanCreate;
};

export type AdminAdminCreatePlanResponse = (PlanPublic);

export type AdminAdminUpdatePlanData = {
    planId: string;
    requestBody: PlanUpdate;
};

export type AdminAdminUpdatePlanResponse = (PlanPublic);

export type AdminAdminDeletePlanData = {
    planId: string;
};

export type AdminAdminDeletePlanResponse = (Message);

export type AiAiHealthResponse = ({
    [key: string]: unknown;
});

export type AiChatStreamData = {
    requestBody: ChatRequest;
};

export type AiChatStreamResponse = (unknown);

export type ApiKeysReadApiKeysResponse = (ApiKeysPublic);

export type ApiKeysCreateApiKeyRouteData = {
    requestBody: ApiKeyCreate;
};

export type ApiKeysCreateApiKeyRouteResponse = (ApiKeyCreated);

export type ApiKeysRevokeApiKeyRouteData = {
    keyId: unknown;
};

export type ApiKeysRevokeApiKeyRouteResponse = (Message);

export type ApiKeysReadApiKeyMeData = {
    xApiKey?: (string | null);
};

export type ApiKeysReadApiKeyMeResponse = ({
    [key: string]: unknown;
});

export type AuthRefreshAccessTokenData = {
    requestBody: RefreshRequest;
};

export type AuthRefreshAccessTokenResponse = (Token);

export type AuthLogoutData = {
    requestBody: RefreshRequest;
};

export type AuthLogoutResponse = (Message);

export type AuthReadSessionsResponse = (SessionsPublic);

export type AuthRevokeSessionRouteData = {
    sessionId: unknown;
};

export type AuthRevokeSessionRouteResponse = (Message);

export type AuthTotpSetupData = {
    requestBody: TotpSetupRequest;
};

export type AuthTotpSetupResponse = (TotpSetupResponse);

export type AuthTotpEnableData = {
    requestBody: TotpEnableRequest;
};

export type AuthTotpEnableResponse = (Message);

export type AuthTotpDisableData = {
    requestBody: TotpDisableRequest;
};

export type AuthTotpDisableResponse = (Message);

export type AuthAuthProvidersResponse = ({
    [key: string]: Array<(string)>;
});

export type AuthAuthLoginData = {
    provider: string;
};

export type AuthAuthLoginResponse = (unknown);

export type AuthOauthCallbackData = {
    provider: string;
};

export type AuthOauthCallbackResponse = (unknown);

export type FilesUploadData = {
    formData: Body_files_upload;
};

export type FilesUploadResponse = ({
    [key: string]: (string);
});

export type FilesDownloadData = {
    fileName: string;
    organizationId: string;
};

export type FilesDownloadResponse = (unknown);

export type ItemsReadItemsData = {
    cursor?: (string | null);
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadAllItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadAllItemsResponse = (ItemsPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MetricsMetricsData = {
    authorization?: (string | null);
};

export type MetricsMetricsResponse = (unknown);

export type NotificationsReadNotificationsResponse = (NotificationsPublic);

export type NotificationsUnreadCountResponse = ({
    [key: string]: (number);
});

export type NotificationsMarkReadRouteData = {
    notificationId: unknown;
};

export type NotificationsMarkReadRouteResponse = (NotificationPublic);

export type NotificationsMarkAllReadRouteResponse = ({
    [key: string]: (number);
});

export type OrganizationsReadMyOrganizationsResponse = ({
    [key: string]: unknown;
});

export type OrganizationsCreateOrganizationRouteData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationRouteResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    organizationId: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationRouteData = {
    organizationId: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationRouteResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    organizationId: string;
};

export type OrganizationsDeleteOrganizationResponse = (Message);

export type OrganizationsReadMembersData = {
    organizationId: string;
};

export type OrganizationsReadMembersResponse = (OrganizationMembersPublic);

export type OrganizationsInviteMemberData = {
    organizationId: string;
    requestBody: OrganizationInviteCreate;
};

export type OrganizationsInviteMemberResponse = (OrganizationInvitePublic);

export type OrganizationsReadInvitesData = {
    organizationId: string;
};

export type OrganizationsReadInvitesResponse = (OrganizationInvitesPublic);

export type OrganizationsAcceptInviteData = {
    token: string;
};

export type OrganizationsAcceptInviteResponse = (Message);

export type OrganizationsUpdateMemberRoleRouteData = {
    organizationId: string;
    role: string;
    userId: string;
};

export type OrganizationsUpdateMemberRoleRouteResponse = (OrganizationMemberPublic);

export type OrganizationsRemoveMemberRouteData = {
    organizationId: string;
    userId: string;
};

export type OrganizationsRemoveMemberRouteResponse = (Message);

export type OrganizationsSuspendOrganizationData = {
    organizationId: string;
};

export type OrganizationsSuspendOrganizationResponse = (OrganizationPublic);

export type OrganizationsUnsuspendOrganizationData = {
    organizationId: string;
};

export type OrganizationsUnsuspendOrganizationResponse = (OrganizationPublic);

export type OrganizationsExportOrganizationData = {
    organizationId: string;
};

export type OrganizationsExportOrganizationResponse = ({
    [key: string]: unknown;
});

export type OrganizationsRevokeInviteData = {
    inviteId: string;
    organizationId: string;
};

export type OrganizationsRevokeInviteResponse = (Message);

export type OrganizationsResendInviteData = {
    inviteId: string;
    organizationId: string;
};

export type OrganizationsResendInviteResponse = (OrganizationInvitePublic);

export type OrganizationsDeclineInviteData = {
    token: string;
};

export type OrganizationsDeclineInviteResponse = (Message);

export type OrganizationsTransferOwnershipData = {
    organizationId: string;
    userId: string;
};

export type OrganizationsTransferOwnershipResponse = (Message);

export type OrganizationsLeaveOrganizationData = {
    organizationId: string;
};

export type OrganizationsLeaveOrganizationResponse = (Message);

export type PaymentsReadPlansResponse = (PlansPublic);

export type PaymentsCreateCheckoutData = {
    planId: string;
};

export type PaymentsCreateCheckoutResponse = ({
    [key: string]: (string);
});

export type PaymentsChangePlanData = {
    planId: string;
};

export type PaymentsChangePlanResponse = (SubscriptionPublic);

export type PaymentsPaymentsWebhookResponse = ({
    [key: string]: (boolean);
});

export type PaymentsReadSubscriptionResponse = ((SubscriptionPublic | null));

export type PaymentsCancelSubscriptionResponse = (Message);

export type PaymentsBillingPortalResponse = ({
    [key: string]: (string);
});

export type PaymentsGetUsageMetricsResponse = ({
    [key: string]: unknown;
});

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PublicPublicConfigResponse = (PublicConfig);

export type SamlSamlMetadataResponse = (unknown);

export type SamlSamlLoginResponse = (unknown);

export type SamlSamlAcsResponse = (unknown);

export type SamlSamlStatusResponse = (Message);

export type ScimServiceProviderConfigResponse = ({
    [key: string]: unknown;
});

export type ScimListScimUsersData = {
    authorization?: (string | null);
    count?: number;
    startIndex?: number;
    xApiKey?: (string | null);
};

export type ScimListScimUsersResponse = ({
    [key: string]: unknown;
});

export type ScimCreateScimUserData = {
    authorization?: (string | null);
    requestBody: ScimUserRequest;
    xApiKey?: (string | null);
};

export type ScimCreateScimUserResponse = ({
    [key: string]: unknown;
});

export type ScimGetScimUserData = {
    authorization?: (string | null);
    userId: string;
    xApiKey?: (string | null);
};

export type ScimGetScimUserResponse = ({
    [key: string]: unknown;
});

export type ScimPatchScimUserData = {
    authorization?: (string | null);
    requestBody: ScimPatchRequest;
    userId: string;
    xApiKey?: (string | null);
};

export type ScimPatchScimUserResponse = ({
    [key: string]: unknown;
});

export type ScimDeleteScimUserData = {
    authorization?: (string | null);
    userId: string;
    xApiKey?: (string | null);
};

export type ScimDeleteScimUserResponse = (void);

export type ScimListScimGroupsData = {
    authorization?: (string | null);
    xApiKey?: (string | null);
};

export type ScimListScimGroupsResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    cursor?: (string | null);
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserAccessResponse = (UserAccess);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersVerifyEmailData = {
    requestBody: VerifyEmailRequest;
};

export type UsersVerifyEmailResponse = (Message);

export type UsersResendVerificationEmailData = {
    requestBody: ResendVerificationEmail;
};

export type UsersResendVerificationEmailResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadinessResponse = ({
    [key: string]: (string);
});

export type WebhooksReadWebhooksResponse = (WebhooksPublic);

export type WebhooksCreateWebhookRouteData = {
    requestBody: WebhookCreate;
};

export type WebhooksCreateWebhookRouteResponse = (WebhookPublic);

export type WebhooksReadWebhookData = {
    webhookId: unknown;
};

export type WebhooksReadWebhookResponse = (WebhookPublic);

export type WebhooksUpdateWebhookRouteData = {
    requestBody: WebhookUpdate;
    webhookId: unknown;
};

export type WebhooksUpdateWebhookRouteResponse = (WebhookPublic);

export type WebhooksDeleteWebhookData = {
    webhookId: unknown;
};

export type WebhooksDeleteWebhookResponse = (Message);

export type WebhooksTestWebhookData = {
    webhookId: unknown;
};

export type WebhooksTestWebhookResponse = (Message);

export type WebhooksReadDeliveriesData = {
    webhookId: unknown;
};

export type WebhooksReadDeliveriesResponse = (WebhookDeliveriesPublic);