"""Add usage metering + billing fields (trial_days, org attribution, quantity)

Revision ID: b4c8f2a6d1e3
Revises: f3a6c9d1e4b2
Create Date: 2026-07-31 20:30:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4c8f2a6d1e3'
down_revision = 'f3a6c9d1e4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('trial_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('paymentevent', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_paymentevent_organization_id'), 'paymentevent', ['organization_id'], unique=False)
    op.create_foreign_key('fk_paymentevent_organization_id', 'paymentevent', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('subscription', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))

    op.create_table(
        'usageevent',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('meter', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_usageevent_meter'), 'usageevent', ['meter'], unique=False)
    op.create_index(op.f('ix_usageevent_organization_id'), 'usageevent', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usageevent_organization_id'), table_name='usageevent')
    op.drop_index(op.f('ix_usageevent_meter'), table_name='usageevent')
    op.drop_table('usageevent')
    op.drop_column('subscription', 'quantity')
    op.drop_constraint('fk_paymentevent_organization_id', 'paymentevent', type_='foreignkey')
    op.drop_index(op.f('ix_paymentevent_organization_id'), table_name='paymentevent')
    op.drop_column('paymentevent', 'organization_id')
    op.drop_column('plan', 'trial_days')
    # ### end Alembic commands ###
