"""Add enterprise features: OAuth accounts, plans, subscriptions, payment events

Revision ID: c4d0e9f1a2b3
Revises: fe56fa70289e
Create Date: 2026-07-31 12:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4d0e9f1a2b3'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Users may authenticate exclusively via a social provider
    op.alter_column('user', 'hashed_password', existing_type=sa.String(length=255), nullable=True)

    op.create_table(
        'oauthaccount',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('provider_account_id', sa.String(length=255), nullable=False),
        sa.Column('provider_email', sa.String(length=255), nullable=True),
        sa.Column('access_token', sa.String(length=2048), nullable=True),
        sa.Column('refresh_token', sa.String(length=2048), nullable=True),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider', 'provider_account_id', name='uq_oauthaccount_provider_account'),
    )
    op.create_index(op.f('ix_oauthaccount_provider'), 'oauthaccount', ['provider'], unique=False)

    op.create_table(
        'plan',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('amount_cents', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('billing_interval', sa.String(length=20), nullable=False),
        sa.Column('provider_plan_id', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('features', sa.String(length=2000), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_plan_slug'), 'plan', ['slug'], unique=True)

    op.create_table(
        'subscription',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('provider', sa.String(length=20), nullable=False),
        sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
        sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_subscription_provider'), 'subscription', ['provider'], unique=False)
    op.create_index(op.f('ix_subscription_provider_subscription_id'), 'subscription', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscription_status'), 'subscription', ['status'], unique=False)

    op.create_table(
        'paymentevent',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('provider', sa.String(length=20), nullable=False),
        sa.Column('provider_event_id', sa.String(length=255), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('amount_cents', sa.Integer(), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('raw', sa.String(length=10000), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_paymentevent_event_type'), 'paymentevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_paymentevent_provider'), 'paymentevent', ['provider'], unique=False)
    op.create_index(op.f('ix_paymentevent_provider_event_id'), 'paymentevent', ['provider_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymentevent_provider_event_id'), table_name='paymentevent')
    op.drop_index(op.f('ix_paymentevent_provider'), table_name='paymentevent')
    op.drop_index(op.f('ix_paymentevent_event_type'), table_name='paymentevent')
    op.drop_table('paymentevent')
    op.drop_index(op.f('ix_subscription_status'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_provider_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_provider'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_plan_slug'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_oauthaccount_provider'), table_name='oauthaccount')
    op.drop_table('oauthaccount')
    op.alter_column('user', 'hashed_password', existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###
