"""Add role and is_verified to User

Revision ID: d7e5f3a9b1c2
Revises: c4d0e9f1a2b3
Create Date: 2026-07-31 14:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7e5f3a9b1c2'
down_revision = 'c4d0e9f1a2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('role', sa.String(length=30), server_default='user', nullable=False),
    )
    op.add_column(
        'user',
        sa.Column('is_verified', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
