"""Add organizations, memberships, invites and tenant scoping

Revision ID: e2f4d0a8c3b1
Revises: d7e5f3a9b1c2
Create Date: 2026-07-31 16:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2f4d0a8c3b1'
down_revision = 'd7e5f3a9b1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'organization',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_organization_slug'), 'organization', ['slug'], unique=True)

    op.create_table(
        'organizationmember',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('role', sa.String(length=30), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_member'),
    )

    op.create_table(
        'organizationinvite',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=30), nullable=False),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('invited_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_organizationinvite_email'), 'organizationinvite', ['email'], unique=False)
    op.create_index(op.f('ix_organizationinvite_token'), 'organizationinvite', ['token'], unique=True)

    op.add_column('item', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_item_organization_id', 'item', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')

    op.add_column('subscription', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_subscription_organization_id', 'subscription', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subscription', 'user_id', existing_type=postgresql.UUID(as_uuid=True), nullable=True)

    op.add_column('plan', sa.Column('quotas', sa.String(length=2000), nullable=True))

    # Backfill: give every existing user a personal organization and re-scope
    # their items and subscriptions to it.
    op.execute(
        """
        INSERT INTO organization (id, name, slug, created_at)
        SELECT
            uuid_generate_v4(),
            COALESCE(u.full_name, u.email, 'My Workspace'),
            'personal-' || left(replace(u.id::text, '-', ''), 12),
            NOW()
        FROM "user" u
        WHERE NOT EXISTS (
            SELECT 1 FROM organizationmember om
            JOIN organization o ON o.id = om.organization_id
            WHERE om.user_id = u.id AND om.role = 'owner'
        )
        """
    )
    op.execute(
        """
        INSERT INTO organizationmember (id, organization_id, user_id, role, created_at)
        SELECT
            uuid_generate_v4(),
            o.id,
            u.id,
            'owner',
            NOW()
        FROM "user" u
        JOIN organization o ON o.slug = 'personal-' || left(replace(u.id::text, '-', ''), 12)
        WHERE NOT EXISTS (
            SELECT 1 FROM organizationmember om
            WHERE om.user_id = u.id AND om.role = 'owner'
        )
        """
    )
    op.execute(
        """
        UPDATE item SET organization_id = (
            SELECT o.id FROM organization o
            JOIN organizationmember om ON om.organization_id = o.id
            WHERE om.user_id = item.owner_id AND om.role = 'owner'
            LIMIT 1
        )
        """
    )
    op.execute(
        """
        UPDATE subscription SET organization_id = (
            SELECT o.id FROM organization o
            JOIN organizationmember om ON om.organization_id = o.id
            WHERE om.user_id = subscription.user_id AND om.role = 'owner'
            LIMIT 1
        )
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'quotas')
    op.alter_column('subscription', 'user_id', existing_type=postgresql.UUID(as_uuid=True), nullable=False)
    op.drop_constraint('fk_subscription_organization_id', 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'organization_id')
    op.drop_constraint('fk_item_organization_id', 'item', type_='foreignkey')
    op.drop_column('item', 'organization_id')
    op.drop_index(op.f('ix_organizationinvite_token'), table_name='organizationinvite')
    op.drop_index(op.f('ix_organizationinvite_email'), table_name='organizationinvite')
    op.drop_table('organizationinvite')
    op.drop_table('organizationmember')
    op.drop_index(op.f('ix_organization_slug'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
